### ISSUE TITLE
forge weird behaviors

### ISSUE THREAD

**Issue by ghost** [Varkalandar/imp_city#5] opened 2023-11-07 12:27 UTC
It seems the forge does not consume the "raw resources". The icons still are around, but resource seems to not be considered by forgers (which makes sense) so this might just be a leak.
Also, it seems *either* 1 copper ore *or* 1 tin ore are enough to produce a bunch of bronze, instead of requiring both.

**Comment by Varkalandar** [comment] 2023-11-07 17:31
I can confirm that currently either input is sufficient to produce bronze coins.

I must rework the forge code anyways due to the other change, how rooms are being furnished, so I'll look into this as well. The resources should disappear during production.

**Comment by Varkalandar** [comment] 2023-11-07 19:06
I've published a hotfix for this bug, called "v0.24a".

**Comment by ghost** [comment] 2023-11-07 19:12
I'll give it a round then, just in case I can find other bugs. But don't worry, you do not have to consider each issue I open "emergency or whatever", I'm fine waiting for a fix in a "soon to arrive" release.

**Comment by ghost** [comment] 2023-11-08 15:48
I confirm now both resources are required together (work start without ore, but produces nothing as long as either copper or tin is missing), but the ore icons stay on the floor.

**Comment by ghost** [comment] 2023-11-11 16:29
I confirm that with 0.25 resources are used, all seems fine to me.

**Comment by Varkalandar** [comment] 2023-11-12 13:39
Thank you. I'll keep this ticket open though, because Conians work in the forges even if there are no resources to use. I'll close it once the changes to the AI are done and working.

**Comment by Varkalandar** [comment] 2023-11-13 22:16
Should be fixed in v0.26, except for the fact that either tin or copper ore is required, which is intentional at the moment, even if not correct in regard to real bronze mixtures.

**Closed as completed by Varkalandar** 2023-11-13 22:16 UTC
Labels: bug
